#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

complete -cf sudo

alias cd..='cd ..'
alias ls='ls --color=auto'
alias l='ls -la'
alias ll='ls -lha'
alias vi='nvim'
alias grep='grep --color=auto'
# alias please='sudo'
alias su='su -l'

shopt -s autocd

export PATH="${PATH}:/home/puma/.local/bin"

PS1=$'\[\033[0;36m\]\u05D0\[\033[0m\] '
# PS1='[\u@\h \W]\$ '

. ~/git-completion.bash

neofetch

