#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

complete -cf sudo

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

shopt -s autocd

export PATH="${PATH}:/home/puma/.local/bin"

PS1=$'\[\033[0;36m\]\u05D0\[\033[0m\] '
# PS1='[\u@\h \W]\$ '

. ~/git-completion.bash

neofetch

